export const ToDoItems = [
  {
    title: "gym",
    message: "work on flexibility",
    creatingDate: "2 days ago",
    modifiedDate: "now",
    priority: "1st",
  },
  {
    title: "study",
    message: "research about react",
    creatingDate: "2 days ago",
    modifiedDate: "now",
    priority: "2nd",
  },
  {
    title: "book",
    message: "read the book you just bought",
    creatingDate: "3 days ago",
    modifiedDate: "1 day ago",
    priority: "3rd",
  },
  {
    title: "coding",
    message: "start coding to do",
    creatingDate: "3 days ago",
    modifiedDate: "now",
    priority: "4th",
  },
  {
    title: "cookig",
    message: "prepare healthy snacks",
    creatingDate: "2 days ago",
    modifiedDate: "now",
    priority: "5th",
  },
  {
    title: "music",
    message: "listen Morrisey",
    creatingDate: "2 days ago",
    modifiedDate: "now",
    priority: "6th",
  },
  {
    title: "clean",
    message: "clean your house",
    creatingDate: "2 days ago",
    modifiedDate: "now",
    priority: "7th",
  },
  {
    title: "yoga",
    message: "do yoga for 20 minutes",
    creatingDate: "2 days ago",
    modifiedDate: "now",
    priority: "8th",
  },
  {
    title: "game",
    message: "play detroit become human",
    creatingDate: "5 days ago",
    modifiedDate: "3 days ago",
    priority: "9th",
  },
  {
    title: "drawing",
    message: "finish your art works",
    creatingDate: "4 days ago",
    modifiedDate: "3 day ago",
    priority: "10th",
  },
];
